annotations:
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 1.51
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This Chart will download and install SteamCMD. It will also install Euro truck simulator 2 dedicated server and run it.
home: "https://github.com/Niborian/truecharts_archive/tree/main/stable/ets2ds"
icon: "https://raw.githubusercontent.com/Niborian/truecharts_archive/main/stable/ets2ds/1.0.0/icon.webp"
keywords:
  - ets2ds
  - GameServers
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ets2ds
sources:
  - https://github.com/Niborian/truecharts_archive/tree/main/stable/ets2ds
  - https://hub.docker.com/r/ich777/steamcmd
  - https://www.steampowered.com/
type: application
version: 1.0.0
