image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: ets2@sha256:03e07ac0208728f01b386edd45f443f67f829c6a94892e42ea9b4ca8197dba92
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: true
    ports:
      main-tcp:
        enabled: true
        port: 27015
        protocol: TCP
        targetPort: 27015
      main-udp:
        enabled: true
        port: 27016
        protocol: UDP
        targetPort: 27016
  udpgameport:
    enabled: true
    ports:
      udpgameport-tcp:
        enabled: true
        port: 27017
        protocol: TCP
        targetPort: 27017
      udpgameport-udp:
        enabled: true
        port: 27018
        protocol: UDP
        targetPort: 27018
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1948160" # ETS2 Game ID for SteamCMD
            GAME_PARAMS: ""
            PASSWRD: ""  # Optional: Set password if needed for non-anonymous login
            USERNAME: ""  # Optional: Set Steam credentials here if needed
            VALIDATE: "true"
